In [4]:
params = {'n_neighbors':[3,5,7,9,11,13,15,17,19,21,23]}

In [5]:
type(params)

dict

In [6]:
params['n_neighbors']

[3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23]

In [7]:
from sklearn.neighbors import KNeighborsClassifier

In [8]:
neigh=KNeighborsClassifier()

In [9]:
neigh.set_params(n_neighbors=3)

KNeighborsClassifier(n_neighbors=3)

In [11]:
neigh.get_params

<bound method BaseEstimator.get_params of KNeighborsClassifier(n_neighbors=3)>

In [12]:
import random

def return_10_random(start,end):
    l=[]
    for i in range(10):
        l.append(random.randint(start,end))
    return l

In [20]:
l=return_10_random(0,50)
print(l)

[33, 3, 6, 39, 43, 20, 35, 50, 9, 20]


In [151]:
#generates a random n class classification problem-https://scikit-learn.org/stable/modules/generated/sklearn.datasets.make_classification.html
from sklearn.datasets import make_classification 

#to split data into train and test
from sklearn.model_selection import train_test_split

#to standardise the data-mean=0 and std dev=1-https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html
from sklearn.preprocessing import StandardScaler
import numpy
from tqdm import tqdm
import numpy as np
import seaborn as sns

#to find the eucliadean distance between d dimensional vectors-https://scikit-learn.org/stable/modules/generated/sklearn.metrics.pairwise.euclidean_distances.html
from sklearn.metrics.pairwise import euclidean_distances

#to measure the accuracy
from sklearn.metrics import accuracy_score

In [152]:
x,y=make_classification(n_samples=100,n_features=2,n_informative=2,n_redundant=0,n_classes=2,n_clusters_per_class=2)
print(x)
print("\n")
print(len(x))
print("\n")
print(y)
print("\n")
print(len(y))

[[ 0.29381984  2.2786062 ]
 [-1.12603375 -0.98442834]
 [ 1.05041167 -0.8198469 ]
 [ 0.84708414  0.51696073]
 [ 0.5298698  -2.66437343]
 [ 0.9385736  -1.19199231]
 [ 1.25123944  1.05057635]
 [ 0.89123053 -1.35893223]
 [ 1.34116712  0.18970966]
 [ 1.00251674 -1.01272195]
 [ 1.30146883  0.03628019]
 [ 1.04053479 -0.87577547]
 [ 0.44241166  1.49828721]
 [-1.80551304  0.18573399]
 [ 2.60400173  2.30291049]
 [-0.54637901 -0.89117525]
 [ 0.143582   -1.49810488]
 [-1.12540965  0.92936627]
 [-2.06754971 -0.17955957]
 [-2.55563334  0.38771935]
 [-2.33865685  0.13121519]
 [ 1.15364355 -0.45982547]
 [ 0.99455643 -0.9906531 ]
 [-0.10385586  1.64987009]
 [-1.11622637  0.92117732]
 [-1.34596244 -0.60740735]
 [ 0.25792778  0.26243037]
 [ 1.33749902  1.50975655]
 [-1.00017876 -1.67850185]
 [-1.86998396 -0.02935668]
 [-1.98110827 -0.48956558]
 [-1.27251606 -1.34461267]
 [-1.77070852 -0.37275378]
 [-0.39135558  1.52790896]
 [ 0.81981152  1.15172178]
 [ 1.28457989  0.01495143]
 [-0.40228952 -1.37886711]
 

In [153]:
x_train_fold=np.split(x,10)
y_train_fold=np.split(y,10)
print(x_train_fold)
print(y_train_fold)
print(len(y_train_fold))
print(len(y_train_fold))

[array([[ 0.29381984,  2.2786062 ],
       [-1.12603375, -0.98442834],
       [ 1.05041167, -0.8198469 ],
       [ 0.84708414,  0.51696073],
       [ 0.5298698 , -2.66437343],
       [ 0.9385736 , -1.19199231],
       [ 1.25123944,  1.05057635],
       [ 0.89123053, -1.35893223],
       [ 1.34116712,  0.18970966],
       [ 1.00251674, -1.01272195]]), array([[ 1.30146883,  0.03628019],
       [ 1.04053479, -0.87577547],
       [ 0.44241166,  1.49828721],
       [-1.80551304,  0.18573399],
       [ 2.60400173,  2.30291049],
       [-0.54637901, -0.89117525],
       [ 0.143582  , -1.49810488],
       [-1.12540965,  0.92936627],
       [-2.06754971, -0.17955957],
       [-2.55563334,  0.38771935]]), array([[-2.33865685,  0.13121519],
       [ 1.15364355, -0.45982547],
       [ 0.99455643, -0.9906531 ],
       [-0.10385586,  1.64987009],
       [-1.11622637,  0.92117732],
       [-1.34596244, -0.60740735],
       [ 0.25792778,  0.26243037],
       [ 1.33749902,  1.50975655],
       [-1.0001

In [154]:
print(x_train_fold[0])
print(len(x_train_fold[0]))
print(y_train_fold[0])
print(len(y_train_fold[0]))

[[ 0.29381984  2.2786062 ]
 [-1.12603375 -0.98442834]
 [ 1.05041167 -0.8198469 ]
 [ 0.84708414  0.51696073]
 [ 0.5298698  -2.66437343]
 [ 0.9385736  -1.19199231]
 [ 1.25123944  1.05057635]
 [ 0.89123053 -1.35893223]
 [ 1.34116712  0.18970966]
 [ 1.00251674 -1.01272195]]
10
[0 0 1 1 1 1 1 1 1 1]
10


In [155]:
x_cv=x_train_fold[0]
y_cv=y_train_fold[0]
print(x_cv)
print(y_cv)

[[ 0.29381984  2.2786062 ]
 [-1.12603375 -0.98442834]
 [ 1.05041167 -0.8198469 ]
 [ 0.84708414  0.51696073]
 [ 0.5298698  -2.66437343]
 [ 0.9385736  -1.19199231]
 [ 1.25123944  1.05057635]
 [ 0.89123053 -1.35893223]
 [ 1.34116712  0.18970966]
 [ 1.00251674 -1.01272195]]
[0 0 1 1 1 1 1 1 1 1]


In [156]:
l_input=[fold for fold in x_train_fold]
l_output=[ele for ele in y_train_fold]
print(l_input)
print(l_output)

[array([[ 0.29381984,  2.2786062 ],
       [-1.12603375, -0.98442834],
       [ 1.05041167, -0.8198469 ],
       [ 0.84708414,  0.51696073],
       [ 0.5298698 , -2.66437343],
       [ 0.9385736 , -1.19199231],
       [ 1.25123944,  1.05057635],
       [ 0.89123053, -1.35893223],
       [ 1.34116712,  0.18970966],
       [ 1.00251674, -1.01272195]]), array([[ 1.30146883,  0.03628019],
       [ 1.04053479, -0.87577547],
       [ 0.44241166,  1.49828721],
       [-1.80551304,  0.18573399],
       [ 2.60400173,  2.30291049],
       [-0.54637901, -0.89117525],
       [ 0.143582  , -1.49810488],
       [-1.12540965,  0.92936627],
       [-2.06754971, -0.17955957],
       [-2.55563334,  0.38771935]]), array([[-2.33865685,  0.13121519],
       [ 1.15364355, -0.45982547],
       [ 0.99455643, -0.9906531 ],
       [-0.10385586,  1.64987009],
       [-1.11622637,  0.92117732],
       [-1.34596244, -0.60740735],
       [ 0.25792778,  0.26243037],
       [ 1.33749902,  1.50975655],
       [-1.0001

In [157]:
l_input.pop(0) #removing the first fold by index 
l_output.pop(0) #removing the first fold by index
print(l_input)
print(l_output)

[array([[ 1.30146883,  0.03628019],
       [ 1.04053479, -0.87577547],
       [ 0.44241166,  1.49828721],
       [-1.80551304,  0.18573399],
       [ 2.60400173,  2.30291049],
       [-0.54637901, -0.89117525],
       [ 0.143582  , -1.49810488],
       [-1.12540965,  0.92936627],
       [-2.06754971, -0.17955957],
       [-2.55563334,  0.38771935]]), array([[-2.33865685,  0.13121519],
       [ 1.15364355, -0.45982547],
       [ 0.99455643, -0.9906531 ],
       [-0.10385586,  1.64987009],
       [-1.11622637,  0.92117732],
       [-1.34596244, -0.60740735],
       [ 0.25792778,  0.26243037],
       [ 1.33749902,  1.50975655],
       [-1.00017876, -1.67850185],
       [-1.86998396, -0.02935668]]), array([[-1.98110827, -0.48956558],
       [-1.27251606, -1.34461267],
       [-1.77070852, -0.37275378],
       [-0.39135558,  1.52790896],
       [ 0.81981152,  1.15172178],
       [ 1.28457989,  0.01495143],
       [-0.40228952, -1.37886711],
       [-1.9716347 , -0.04280856],
       [-0.7090

In [158]:
x_train_final=np.concatenate([array for array in l_input])
y_train_final=np.concatenate([array for array in l_output])
print(x_train_final)
print(y_train_final)
print(len(x_train_final))
print(len(y_train_final))

[[ 1.30146883  0.03628019]
 [ 1.04053479 -0.87577547]
 [ 0.44241166  1.49828721]
 [-1.80551304  0.18573399]
 [ 2.60400173  2.30291049]
 [-0.54637901 -0.89117525]
 [ 0.143582   -1.49810488]
 [-1.12540965  0.92936627]
 [-2.06754971 -0.17955957]
 [-2.55563334  0.38771935]
 [-2.33865685  0.13121519]
 [ 1.15364355 -0.45982547]
 [ 0.99455643 -0.9906531 ]
 [-0.10385586  1.64987009]
 [-1.11622637  0.92117732]
 [-1.34596244 -0.60740735]
 [ 0.25792778  0.26243037]
 [ 1.33749902  1.50975655]
 [-1.00017876 -1.67850185]
 [-1.86998396 -0.02935668]
 [-1.98110827 -0.48956558]
 [-1.27251606 -1.34461267]
 [-1.77070852 -0.37275378]
 [-0.39135558  1.52790896]
 [ 0.81981152  1.15172178]
 [ 1.28457989  0.01495143]
 [-0.40228952 -1.37886711]
 [-1.9716347  -0.04280856]
 [-0.70908667  1.25172898]
 [-1.00368605 -0.04234362]
 [ 1.13221463 -0.56336149]
 [-1.92521983  0.05669837]
 [-0.77805272 -1.25473371]
 [-1.67572     0.22973017]
 [-1.42047468  0.51390951]
 [-0.80927762 -1.95041088]
 [ 1.04656222 -0.86736487]
 

In [159]:
print("now x_cv,y_cv and x_train_new,y_train_new have been properly taken out from x_test and y_test \n")
print("x_cv,y_cv has 10 samples out of 100 and x_train_new,y_train_new have 90 samples out of 100 \n")

now x_cv,y_cv and x_train_new,y_train_new have been properly taken out from x_test and y_test 

x_cv,y_cv has 10 samples out of 100 and x_train_new,y_train_new have 90 samples out of 100 

